### ISSUE TITLE
Pour la gestion des ampoules

### ISSUE THREAD

**Issue by yvestan** [HoudaB/carte-voeux#1]
<img width="771" alt="capture d ecran 2016-12-22 a 17 56 18" src="https://cloud.githubusercontent.com/assets/146787/21433452/267289d0-c870-11e6-82db-ef5ad830381d.png">
<img width="543" alt="capture d ecran 2016-12-22 a 17 56 50" src="https://cloud.githubusercontent.com/assets/146787/21433453/26734ac8-c870-11e6-8ab5-1a57fb02ebde.png">

**Comment by HoudaB** [comment]
Merci encore !
